library(datasets)
NZ <- read.table("pounds_nz.dat", header = TRUE)
head(NZ)
class(NZ.ts)
NZ.ts <- ts(NZ, st = 1991, fr = 4)
NZ <- data.frame(date = time(NZ.ts), rate = as.matrix(NZ.ts))
getwd()
setwd("01 Time Series Data")
write.csv(NZ,"pounds_nz.csv",row.names = FALSE)
